---
title: "Answer 872769"
se.owner.user_id: 22836
se.owner.display_name: "4per"
se.owner.link: "https://ru.stackoverflow.com/users/22836/4per"
se.answer_id: 872769
se.question_id: 872684
se.post_type: answer
se.score: 0
se.is_accepted: False
---
<p>Подпишитесь на <code>Application.ThreadException</code></p>

<p>Исключения из ГУИ-потока так ловятся. А вот исключения из прочих потоков, просто крашат приложение, поэтому их пришлось завернуть в <code>try-catch</code> все.</p>
