---
title: "Answer 939423"
se.owner.user_id: 178779
se.owner.display_name: "Pavel Mayorov"
se.owner.link: "https://ru.stackoverflow.com/users/178779/pavel-mayorov"
se.answer_id: 939423
se.question_id: 939158
se.post_type: answer
se.score: 2
se.is_accepted: False
---
<p>Так всё просто же. У вас нет никакой обработки исключений - поэтому первая же сетевая ошибка аварийно завершает процесс.</p>

<p>Добавьте обработку исключений.</p>
